INSERT INTO Avocado (id, ) VALUES ('1');
INSERT INTO Avocado (id, ) VALUES ('2');
INSERT INTO Avocado (id, ) VALUES ('3');
INSERT INTO Avocado (id, ) VALUES ('4');
INSERT INTO Avocado (id,) VALUES ('5');
INSERT INTO Avocado (id, ) VALUES ('6');
INSERT INTO Avocado (id, ) VALUES ('7');
INSERT INTO Avocado (id, ) VALUES ('8');
INSERT INTO Avocado (id, ) VALUES ('9');
INSERT INTO Avocado (id, ) VALUES ('10');
INSERT INTO Avocado (id, ) VALUES ('11');
INSERT INTO Avocado (id,) VALUES ('12');
INSERT INTO Avocado (id,) VALUES ('13');
INSERT INTO Avocado (id, ) VALUES ('14');
INSERT INTO Avocado (id) VALUES ('15');

INSERT INTO Regions (id, region) VALUES ('1', 'Albany');
INSERT INTO Regions (id, region) VALUES ('15', 'Albany');
INSERT INTO Regions (id,region) VALUES ('2','Atlanta');
INSERT INTO Regions (id,region) VALUES ('3','Atlanta');
INSERT INTO Regions (id,region) VALUES ('4', 'BaltimoreWashington');
INSERT INTO Regions (id,region) VALUES ('5','Boise');
INSERT INTO Regions (id,region) VALUES ('6','Boise');
INSERT INTO Regions (id,region) VALUES ('7','Boise');
INSERT INTO Regions (id,region) VALUES ('8','Boise');
INSERT INTO Regions (id,region) VALUES ('9','Boston');
INSERT INTO Regions (id,region) VALUES ('10','BuffaloRochester');
INSERT INTO Regions (id,region) VALUES ('11','BuffaloRochester');
INSERT INTO Regions (id,region) VALUES ('12','BuffaloRochester');
INSERT INTO Regions (id,region) VALUES ('13','California');
INSERT INTO Regions (id,region) VALUES ('14','California');

INSERT INTO Months (id, month) VALUES ('1', '12');
INSERT INTO Months (id, month) VALUES ('2', '12');
INSERT INTO Months (id,  month) VALUES ('3',  '12');
INSERT INTO Months (id,  month) VALUES ('4', '11');
INSERT INTO Months (id,  month) VALUES ('5',  '11');
INSERT INTO Months (id,  month) VALUES ('6',  '11');
INSERT INTO Months (id,  month) VALUES ('7',  '11');
INSERT INTO Months (id,  month) VALUES ('8',  '11');
INSERT INTO Months (id, month) VALUES ('9', '10');
INSERT INTO Months (id,  month) VALUES ('10', '10');
INSERT INTO Months (id,  month) VALUES ('11',  '10');
INSERT INTO Months (id,  month) VALUES ('12', '10');
INSERT INTO Months (id,  month) VALUES ('13',  '09');
INSERT INTO Months (id,  month) VALUES ('14',  '08');
INSERT INTO Months (id, month) VALUES ('15','12');


INSERT INTO Prices (id,avgprice) VALUES ('10','1,33');
INSERT INTO Prices (id,avgprice) VALUES ('15','1,33');
INSERT INTO Prices (id,avgprice) VALUES ('1', '1,35');
INSERT INTO Prices (id,avgprice) VALUES ('2', '0,93');
INSERT INTO Prices (id,avgprice) VALUES ('3','1,02');
INSERT INTO Prices (id,avgprice) VALUES ('4','1,00');
INSERT INTO Prices (id,avgprice) VALUES ('9','1,00');
INSERT INTO Prices (id,avgprice) VALUES ('5','0,88');
INSERT INTO Prices (id,avgprice) VALUES ('6','0,92');
INSERT INTO Prices (id,avgprice) VALUES ('7', '1,11');
INSERT INTO Prices (id,avgprice) VALUES ('11', '1,20');
INSERT INTO Prices (id,avgprice) VALUES ('8', '1,03');
INSERT INTO Prices (id,avgprice) VALUES ('12', '1,23');
INSERT INTO Prices (id,avgprice) VALUES ('13','0,99');
INSERT INTO Prices (id,avgprice) VALUES ('14', '1,21');

